#!/usr/bin/env python
from gpiozero import LED

def status():
    """Prints the status of the monitor ("on" or "off")"""
    relayPin=25
    if LED(relayPin).value==1: #active=HIGH=monitor off
        return "off"
    else:
        return "on"

print(status()) #goes to STDOUT
