#!/usr/bin/env python
from gpiozero import LED

def status():
    relayPin=23
    if LED(relayPin).value==1: #active=HIGH=monitor off
        print("off")
    else:
        print("on")

print(status()) #goes to STDOUT
