#!/bin/bash

ls /sys/class/gpio/gpio25 > /dev/null 2>&1 || ( echo 25 > /sys/class/gpio/export; sleep 0.1 )

if [ "$(cat /sys/class/gpio/gpio25/value)" -eq "1" ]; then #if the relay is HIGH, then off
    echo "off"
else
    echo "on"
fi
