#!/usr/bin/env python

# ABOUT: outputs a HIGH signal to the relay through GPIO pin #14. The monitor, which is connected to "normally on", turns off.
# Result: turns OFF monitor
# Created on 9.30.22
# Last modified 10.22.22

from gpiozero import LED

led=LED(14)
LED.on()

