#!/usr/bin/env python

# ABOUT: outputs a HIGH signal to the relay through GPIO pin #14. The monitor, which is connected to "normally on", turns off.
# Result: turns OFF monitor
# Created on 9.30.22
# Last modified 10.1.22

import RPi.GPIO as GPIO
from time import sleep

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(14, GPIO.OUT) #relay pin
GPIO.output(14, GPIO.HIGH)
