#!/usr/bin/env python

# ABOUT: outputs a LOW signal to the relay through GPIO pin #14. The monitor, which is connected to "normally on", turns on.
# Result: turns ON monitor
# Created on 9.30.22
# Last modified 10.1.22

import RPi.GPIO as GPIO

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(14, GPIO.OUT) #relay pin

GPIO.output(14, GPIO.LOW)
